# Generated by Django 5.0 on 2023-12-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelIQ", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="symbol",
            field=models.CharField(max_length=10),
        ),
    ]
