# Generated by Django 5.0 on 2023-12-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelIQ", "0002_alter_cryptocurrency_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptocurrency",
            name="last_7_days_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
