# Generated by Django 5.0 on 2023-12-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelIQ", "0003_cryptocurrency_last_7_days_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="last_7_days_data",
            field=models.ImageField(blank=True, null=True, upload_to="chart_images/"),
        ),
    ]
