# Generated by Django 5.0 on 2023-12-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelIQ", "0004_alter_cryptocurrency_last_7_days_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="last_7_days_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
